# Generated by Django 2.2.6 on 2019-11-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='price',
            field=models.CharField(max_length=30),
        ),
    ]
