# Generated by Django 2.2.6 on 2019-11-25 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0002_auto_20191122_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptops.Laptop')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('spec', models.CharField(max_length=30)),
                ('laptops', models.ManyToManyField(related_name='programs', through='laptops.Info', to='laptops.Laptop')),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptops.Program'),
        ),
    ]
