# Generated by Django 2.2.6 on 2019-11-25 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0003_auto_20191125_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='program',
            name='laptops',
        ),
        migrations.AddField(
            model_name='info',
            name='spec',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='laptops.Spec'),
            preserve_default=False,
        ),
    ]
